// AUTOGENERATED, DO NOT EDIT
// Type definitions for server implementations of ports.
// package: decentraland.renderer.kernel_services
// file: decentraland/renderer/kernel_services/analytics.proto
using System.Collections.Generic;
using System.Threading;
using Cysharp.Threading.Tasks;
using Google.Protobuf;
using rpc_csharp.protocol;
using rpc_csharp;
namespace Decentraland.Renderer.KernelServices {
public interface IAnalyticsKernelService<Context>
{

  UniTask<PerformanceReportResponse> PerformanceReport(PerformanceReportRequest request, Context context, CancellationToken ct);

  UniTask<SystemInfoReportResponse> SystemInfoReport(SystemInfoReportRequest request, Context context, CancellationToken ct);

  UniTask<AnalyticsEventResponse> AnalyticsEvent(AnalyticsEventRequest request, Context context, CancellationToken ct);

  UniTask<DelightedSurveyResponse> SetDelightedSurveyEnabled(DelightedSurveyRequest request, Context context, CancellationToken ct);

}

public static class AnalyticsKernelServiceCodeGen
{
  public const string ServiceName = "AnalyticsKernelService";

  public static void RegisterService<Context>(RpcServerPort<Context> port, IAnalyticsKernelService<Context> service)
  {
    var result = new ServerModuleDefinition<Context>();
      
    result.definition.Add("PerformanceReport", async (payload, context, ct) => { var res = await service.PerformanceReport(PerformanceReportRequest.Parser.ParseFrom(payload), context, ct); return res?.ToByteString(); });
    result.definition.Add("SystemInfoReport", async (payload, context, ct) => { var res = await service.SystemInfoReport(SystemInfoReportRequest.Parser.ParseFrom(payload), context, ct); return res?.ToByteString(); });
    result.definition.Add("AnalyticsEvent", async (payload, context, ct) => { var res = await service.AnalyticsEvent(AnalyticsEventRequest.Parser.ParseFrom(payload), context, ct); return res?.ToByteString(); });
    result.definition.Add("SetDelightedSurveyEnabled", async (payload, context, ct) => { var res = await service.SetDelightedSurveyEnabled(DelightedSurveyRequest.Parser.ParseFrom(payload), context, ct); return res?.ToByteString(); });

    port.RegisterModule(ServiceName, (port) => UniTask.FromResult(result));
  }
}
}
