
// AUTOGENERATED, DO NOT EDIT
// Type definitions for server implementations of ports.
// package: 
// file: decentraland/renderer/renderer_services/emotes_renderer.proto
using Cysharp.Threading.Tasks;
using rpc_csharp;

public class ClientEmotesRendererService
{
  private readonly RpcClientModule module;

  public ClientEmotesRendererService(RpcClientModule module)
  {
      this.module = module;
  }

  public UniTask<TriggerSelfUserExpressionResponse> TriggerSelfUserExpression(TriggerSelfUserExpressionRequest request)
  {
      return module.CallUnaryProcedure<TriggerSelfUserExpressionResponse>("TriggerSelfUserExpression", request);
  }
}
