
// AUTOGENERATED, DO NOT EDIT
// Type definitions for server implementations of ports.
// package: 
// file: decentraland/renderer/renderer_services/friend_request_renderer.proto
using Cysharp.Threading.Tasks;
using rpc_csharp;

public class ClientFriendRequestRendererService
{
  private readonly RpcClientModule module;

  public ClientFriendRequestRendererService(RpcClientModule module)
  {
      this.module = module;
  }

  public UniTask<AddFriendRequestReply> AddFriendRequest(AddFriendRequestPayload request)
  {
      return module.CallUnaryProcedure<AddFriendRequestReply>("AddFriendRequest", request);
  }
}
