public enum InternalECSComponentsId
{
    // TRANSFORM = 1 // we already have TRANSFORM component as id = 1
    TEXTURIZABLE = 2,
    MATERIAL = 3,
    COLLIDER_POINTER = 4,
    COLLIDER_PHYSICAL = 5,
    RENDERERS = 6,
    VISIBILITY = 7,
    INPUT_EVENTS_RESULT = 8,
    UI_CONTAINER = 9,
    UI_INPUT_EVENTS_RESULT = 10,
    VIDEO_PLAYER = 11,
    VIDEO_MATERIAL = 12,
    SCENE_BOUNDS_CHECK = 13,
    AUDIO_SOURCE = 14,
    POINTER_EVENTS = 15,
    REGISTERED_UI_POINTER_EVENTS = 16,
    COLLIDER_CUSTOM = 17,
    RAYCAST = 18,
    GLTF_CONTAINER_LOADING_STATE = 19,
    ENGINE_INFO = 20
}
