
// AUTOGENERATED, DO NOT EDIT
// Type definitions for server implementations of ports.
// package: decentraland.renderer.renderer_services
// file: decentraland/renderer/renderer_services/restricted_actions.proto
using Cysharp.Threading.Tasks;
using rpc_csharp;

namespace Decentraland.Renderer.RendererServices {
public interface IClientRestrictedActionsService
{
  UniTask<OpenModalResponse> OpenExternalUrl(OpenExternalUrlRequest request);

  UniTask<OpenModalResponse> OpenNftDialog(OpenNftDialogRequest request);
}

public class ClientRestrictedActionsService : IClientRestrictedActionsService
{
  private readonly RpcClientModule module;

  public ClientRestrictedActionsService(RpcClientModule module)
  {
      this.module = module;
  }


  public UniTask<OpenModalResponse> OpenExternalUrl(OpenExternalUrlRequest request)
  {
      return module.CallUnaryProcedure<OpenModalResponse>("OpenExternalUrl", request);
  }

  public UniTask<OpenModalResponse> OpenNftDialog(OpenNftDialogRequest request)
  {
      return module.CallUnaryProcedure<OpenModalResponse>("OpenNftDialog", request);
  }

}
}
