// AUTOGENERATED, DO NOT EDIT
// Type definitions for server implementations of ports.
// package: decentraland.renderer.renderer_services
// file: decentraland/renderer/renderer_services/emotes_renderer.proto
using System.Collections.Generic;
using System.Threading;
using Cysharp.Threading.Tasks;
using Google.Protobuf;
using rpc_csharp.protocol;
using rpc_csharp;
namespace Decentraland.Renderer.RendererServices {
public interface IEmotesRendererService<Context>
{

  UniTask<TriggerSelfUserExpressionResponse> TriggerSelfUserExpression(TriggerSelfUserExpressionRequest request, Context context, CancellationToken ct);

}

public static class EmotesRendererServiceCodeGen
{
  public const string ServiceName = "EmotesRendererService";

  public static void RegisterService<Context>(RpcServerPort<Context> port, IEmotesRendererService<Context> service)
  {
    var result = new ServerModuleDefinition<Context>();
      
    result.definition.Add("TriggerSelfUserExpression", async (payload, context, ct) => { var res = await service.TriggerSelfUserExpression(TriggerSelfUserExpressionRequest.Parser.ParseFrom(payload), context, ct); return res?.ToByteString(); });

    port.RegisterModule(ServiceName, (port) => UniTask.FromResult(result));
  }
}
}
