// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: decentraland/sdk/components/audio_source.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DCL.ECSComponents {

  /// <summary>Holder for reflection information generated from decentraland/sdk/components/audio_source.proto</summary>
  public static partial class AudioSourceReflection {

    #region Descriptor
    /// <summary>File descriptor for decentraland/sdk/components/audio_source.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AudioSourceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5kZWNlbnRyYWxhbmQvc2RrL2NvbXBvbmVudHMvYXVkaW9fc291cmNlLnBy",
            "b3RvEhtkZWNlbnRyYWxhbmQuc2RrLmNvbXBvbmVudHMi7wEKDVBCQXVkaW9T",
            "b3VyY2USFAoHcGxheWluZxgBIAEoCEgAiAEBEhMKBnZvbHVtZRgCIAEoAkgB",
            "iAEBEhEKBGxvb3AYAyABKAhIAogBARISCgVwaXRjaBgEIAEoAkgDiAEBEhYK",
            "DmF1ZGlvX2NsaXBfdXJsGAUgASgJEhkKDGN1cnJlbnRfdGltZRgGIAEoAkgE",
            "iAEBEhMKBmdsb2JhbBgHIAEoCEgFiAEBQgoKCF9wbGF5aW5nQgkKB192b2x1",
            "bWVCBwoFX2xvb3BCCAoGX3BpdGNoQg8KDV9jdXJyZW50X3RpbWVCCQoHX2ds",
            "b2JhbEIUqgIRRENMLkVDU0NvbXBvbmVudHNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DCL.ECSComponents.PBAudioSource), global::DCL.ECSComponents.PBAudioSource.Parser, new[]{ "Playing", "Volume", "Loop", "Pitch", "AudioClipUrl", "CurrentTime", "Global" }, new[]{ "Playing", "Volume", "Loop", "Pitch", "CurrentTime", "Global" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// The AudioSource component can play an audio clips bundled with the scene, controlling some
  /// of the behavior.
  ///
  /// In each AudioSource instance, the sound is spatially located at the associated entity’s position,
  /// given by its Transform.
  ///
  /// Note that the `audio_clip_url` is not actually a URL, but rather the path of a file bundled with
  /// the scene and declared in its manifest. The name was chosen because the URL use-case will
  /// eventually be supported.
  ///
  /// `playing=true` when it's previously `playing=true`
  ///  a) if clip is playing and `current_time` is NOT SET, the clip remains in the current `current_time`
  ///  b) if clip is stopped or `current_time` is set, the clip is played from the `current_time` (if set) or from the beginning
  ///
  /// If other property (volume, loop, pitch) is changed while playing, the clip is keep playing with the new properties
  /// Changing `audio_clip_url` while playing stops the current clip and plays the new one (as a new instance)
  /// </summary>
  public sealed partial class PBAudioSource : pb::IMessage<PBAudioSource>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PBAudioSource> _parser = new pb::MessageParser<PBAudioSource>(() => new PBAudioSource());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PBAudioSource> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DCL.ECSComponents.AudioSourceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBAudioSource() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBAudioSource(PBAudioSource other) : this() {
      _hasBits0 = other._hasBits0;
      playing_ = other.playing_;
      volume_ = other.volume_;
      loop_ = other.loop_;
      pitch_ = other.pitch_;
      audioClipUrl_ = other.audioClipUrl_;
      currentTime_ = other.currentTime_;
      global_ = other.global_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBAudioSource Clone() {
      return new PBAudioSource(this);
    }

    /// <summary>Field number for the "playing" field.</summary>
    public const int PlayingFieldNumber = 1;
    private bool playing_;
    /// <summary>
    /// whether the clip is currently playing.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Playing {
      get { if ((_hasBits0 & 1) != 0) { return playing_; } else { return false; } }
      set {
        _hasBits0 |= 1;
        playing_ = value;
      }
    }
    /// <summary>Gets whether the "playing" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPlaying {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "playing" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPlaying() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "volume" field.</summary>
    public const int VolumeFieldNumber = 2;
    private float volume_;
    /// <summary>
    /// the audio volume (default: 1.0).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Volume {
      get { if ((_hasBits0 & 2) != 0) { return volume_; } else { return 0F; } }
      set {
        _hasBits0 |= 2;
        volume_ = value;
      }
    }
    /// <summary>Gets whether the "volume" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasVolume {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "volume" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearVolume() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "loop" field.</summary>
    public const int LoopFieldNumber = 3;
    private bool loop_;
    /// <summary>
    /// whether the clip should restart when finished.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Loop {
      get { if ((_hasBits0 & 4) != 0) { return loop_; } else { return false; } }
      set {
        _hasBits0 |= 4;
        loop_ = value;
      }
    }
    /// <summary>Gets whether the "loop" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLoop {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "loop" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLoop() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "pitch" field.</summary>
    public const int PitchFieldNumber = 4;
    private float pitch_;
    /// <summary>
    /// the audio pitch (default: 1.0).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Pitch {
      get { if ((_hasBits0 & 8) != 0) { return pitch_; } else { return 0F; } }
      set {
        _hasBits0 |= 8;
        pitch_ = value;
      }
    }
    /// <summary>Gets whether the "pitch" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPitch {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "pitch" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPitch() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "audio_clip_url" field.</summary>
    public const int AudioClipUrlFieldNumber = 5;
    private string audioClipUrl_ = "";
    /// <summary>
    /// the clip path as given in the `files` array of the scene's manifest.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AudioClipUrl {
      get { return audioClipUrl_; }
      set {
        audioClipUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "current_time" field.</summary>
    public const int CurrentTimeFieldNumber = 6;
    private float currentTime_;
    /// <summary>
    /// specifies the current playback time of the clip in seconds (default: 0).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float CurrentTime {
      get { if ((_hasBits0 & 16) != 0) { return currentTime_; } else { return 0F; } }
      set {
        _hasBits0 |= 16;
        currentTime_ = value;
      }
    }
    /// <summary>Gets whether the "current_time" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCurrentTime {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "current_time" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCurrentTime() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "global" field.</summary>
    public const int GlobalFieldNumber = 7;
    private bool global_;
    /// <summary>
    /// whether the audio plays at constant volume across the scene.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Global {
      get { if ((_hasBits0 & 32) != 0) { return global_; } else { return false; } }
      set {
        _hasBits0 |= 32;
        global_ = value;
      }
    }
    /// <summary>Gets whether the "global" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGlobal {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "global" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGlobal() {
      _hasBits0 &= ~32;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PBAudioSource);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PBAudioSource other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Playing != other.Playing) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Volume, other.Volume)) return false;
      if (Loop != other.Loop) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Pitch, other.Pitch)) return false;
      if (AudioClipUrl != other.AudioClipUrl) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(CurrentTime, other.CurrentTime)) return false;
      if (Global != other.Global) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPlaying) hash ^= Playing.GetHashCode();
      if (HasVolume) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Volume);
      if (HasLoop) hash ^= Loop.GetHashCode();
      if (HasPitch) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Pitch);
      if (AudioClipUrl.Length != 0) hash ^= AudioClipUrl.GetHashCode();
      if (HasCurrentTime) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(CurrentTime);
      if (HasGlobal) hash ^= Global.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPlaying) {
        output.WriteRawTag(8);
        output.WriteBool(Playing);
      }
      if (HasVolume) {
        output.WriteRawTag(21);
        output.WriteFloat(Volume);
      }
      if (HasLoop) {
        output.WriteRawTag(24);
        output.WriteBool(Loop);
      }
      if (HasPitch) {
        output.WriteRawTag(37);
        output.WriteFloat(Pitch);
      }
      if (AudioClipUrl.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(AudioClipUrl);
      }
      if (HasCurrentTime) {
        output.WriteRawTag(53);
        output.WriteFloat(CurrentTime);
      }
      if (HasGlobal) {
        output.WriteRawTag(56);
        output.WriteBool(Global);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPlaying) {
        output.WriteRawTag(8);
        output.WriteBool(Playing);
      }
      if (HasVolume) {
        output.WriteRawTag(21);
        output.WriteFloat(Volume);
      }
      if (HasLoop) {
        output.WriteRawTag(24);
        output.WriteBool(Loop);
      }
      if (HasPitch) {
        output.WriteRawTag(37);
        output.WriteFloat(Pitch);
      }
      if (AudioClipUrl.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(AudioClipUrl);
      }
      if (HasCurrentTime) {
        output.WriteRawTag(53);
        output.WriteFloat(CurrentTime);
      }
      if (HasGlobal) {
        output.WriteRawTag(56);
        output.WriteBool(Global);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPlaying) {
        size += 1 + 1;
      }
      if (HasVolume) {
        size += 1 + 4;
      }
      if (HasLoop) {
        size += 1 + 1;
      }
      if (HasPitch) {
        size += 1 + 4;
      }
      if (AudioClipUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AudioClipUrl);
      }
      if (HasCurrentTime) {
        size += 1 + 4;
      }
      if (HasGlobal) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PBAudioSource other) {
      if (other == null) {
        return;
      }
      if (other.HasPlaying) {
        Playing = other.Playing;
      }
      if (other.HasVolume) {
        Volume = other.Volume;
      }
      if (other.HasLoop) {
        Loop = other.Loop;
      }
      if (other.HasPitch) {
        Pitch = other.Pitch;
      }
      if (other.AudioClipUrl.Length != 0) {
        AudioClipUrl = other.AudioClipUrl;
      }
      if (other.HasCurrentTime) {
        CurrentTime = other.CurrentTime;
      }
      if (other.HasGlobal) {
        Global = other.Global;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Playing = input.ReadBool();
            break;
          }
          case 21: {
            Volume = input.ReadFloat();
            break;
          }
          case 24: {
            Loop = input.ReadBool();
            break;
          }
          case 37: {
            Pitch = input.ReadFloat();
            break;
          }
          case 42: {
            AudioClipUrl = input.ReadString();
            break;
          }
          case 53: {
            CurrentTime = input.ReadFloat();
            break;
          }
          case 56: {
            Global = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Playing = input.ReadBool();
            break;
          }
          case 21: {
            Volume = input.ReadFloat();
            break;
          }
          case 24: {
            Loop = input.ReadBool();
            break;
          }
          case 37: {
            Pitch = input.ReadFloat();
            break;
          }
          case 42: {
            AudioClipUrl = input.ReadString();
            break;
          }
          case 53: {
            CurrentTime = input.ReadFloat();
            break;
          }
          case 56: {
            Global = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
