// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: decentraland/sdk/components/common/loading_state.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DCL.ECSComponents {

  /// <summary>Holder for reflection information generated from decentraland/sdk/components/common/loading_state.proto</summary>
  public static partial class LoadingStateReflection {

    #region Descriptor
    /// <summary>File descriptor for decentraland/sdk/components/common/loading_state.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LoadingStateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjZkZWNlbnRyYWxhbmQvc2RrL2NvbXBvbmVudHMvY29tbW9uL2xvYWRpbmdf",
            "c3RhdGUucHJvdG8SImRlY2VudHJhbGFuZC5zZGsuY29tcG9uZW50cy5jb21t",
            "b24qXgoMTG9hZGluZ1N0YXRlEgsKB1VOS05PV04QABILCgdMT0FESU5HEAES",
            "DQoJTk9UX0ZPVU5EEAISFwoTRklOSVNIRURfV0lUSF9FUlJPUhADEgwKCEZJ",
            "TklTSEVEEARCFKoCEURDTC5FQ1NDb21wb25lbnRzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DCL.ECSComponents.LoadingState), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum LoadingState {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("LOADING")] Loading = 1,
    [pbr::OriginalName("NOT_FOUND")] NotFound = 2,
    [pbr::OriginalName("FINISHED_WITH_ERROR")] FinishedWithError = 3,
    [pbr::OriginalName("FINISHED")] Finished = 4,
  }

  #endregion

}

#endregion Designer generated code
