// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: decentraland/common/sdk/user_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Decentraland.Common.Sdk {

  /// <summary>Holder for reflection information generated from decentraland/common/sdk/user_data.proto</summary>
  public static partial class UserDataReflection {

    #region Descriptor
    /// <summary>File descriptor for decentraland/common/sdk/user_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CidkZWNlbnRyYWxhbmQvY29tbW9uL3Nkay91c2VyX2RhdGEucHJvdG8SF2Rl",
            "Y2VudHJhbGFuZC5jb21tb24uc2RrIioKCVNuYXBzaG90cxIPCgdmYWNlMjU2",
            "GAEgASgJEgwKBGJvZHkYAiABKAkirAEKEUF2YXRhckZvclVzZXJEYXRhEhIK",
            "CmJvZHlfc2hhcGUYASABKAkSEgoKc2tpbl9jb2xvchgCIAEoCRISCgpoYWly",
            "X2NvbG9yGAMgASgJEhEKCWV5ZV9jb2xvchgEIAEoCRIRCgl3ZWFyYWJsZXMY",
            "BSADKAkSNQoJc25hcHNob3RzGAYgASgLMiIuZGVjZW50cmFsYW5kLmNvbW1v",
            "bi5zZGsuU25hcHNob3RzIsIBCghVc2VyRGF0YRIUCgxkaXNwbGF5X25hbWUY",
            "ASABKAkSFwoKcHVibGljX2tleRgCIAEoCUgAiAEBEhoKEmhhc19jb25uZWN0",
            "ZWRfd2ViMxgDIAEoCBIPCgd1c2VyX2lkGAQgASgJEg8KB3ZlcnNpb24YBSAB",
            "KAUSOgoGYXZhdGFyGAYgASgLMiouZGVjZW50cmFsYW5kLmNvbW1vbi5zZGsu",
            "QXZhdGFyRm9yVXNlckRhdGFCDQoLX3B1YmxpY19rZXliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Decentraland.Common.Sdk.Snapshots), global::Decentraland.Common.Sdk.Snapshots.Parser, new[]{ "Face256", "Body" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Decentraland.Common.Sdk.AvatarForUserData), global::Decentraland.Common.Sdk.AvatarForUserData.Parser, new[]{ "BodyShape", "SkinColor", "HairColor", "EyeColor", "Wearables", "Snapshots" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Decentraland.Common.Sdk.UserData), global::Decentraland.Common.Sdk.UserData.Parser, new[]{ "DisplayName", "PublicKey", "HasConnectedWeb3", "UserId", "Version", "Avatar" }, new[]{ "PublicKey" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Snapshots : pb::IMessage<Snapshots>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Snapshots> _parser = new pb::MessageParser<Snapshots>(() => new Snapshots());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Snapshots> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Decentraland.Common.Sdk.UserDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Snapshots() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Snapshots(Snapshots other) : this() {
      face256_ = other.face256_;
      body_ = other.body_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Snapshots Clone() {
      return new Snapshots(this);
    }

    /// <summary>Field number for the "face256" field.</summary>
    public const int Face256FieldNumber = 1;
    private string face256_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Face256 {
      get { return face256_; }
      set {
        face256_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "body" field.</summary>
    public const int BodyFieldNumber = 2;
    private string body_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Body {
      get { return body_; }
      set {
        body_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Snapshots);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Snapshots other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Face256 != other.Face256) return false;
      if (Body != other.Body) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Face256.Length != 0) hash ^= Face256.GetHashCode();
      if (Body.Length != 0) hash ^= Body.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Face256.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Face256);
      }
      if (Body.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Body);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Face256.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Face256);
      }
      if (Body.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Body);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Face256.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Face256);
      }
      if (Body.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Body);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Snapshots other) {
      if (other == null) {
        return;
      }
      if (other.Face256.Length != 0) {
        Face256 = other.Face256;
      }
      if (other.Body.Length != 0) {
        Body = other.Body;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Face256 = input.ReadString();
            break;
          }
          case 18: {
            Body = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Face256 = input.ReadString();
            break;
          }
          case 18: {
            Body = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class AvatarForUserData : pb::IMessage<AvatarForUserData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AvatarForUserData> _parser = new pb::MessageParser<AvatarForUserData>(() => new AvatarForUserData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AvatarForUserData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Decentraland.Common.Sdk.UserDataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvatarForUserData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvatarForUserData(AvatarForUserData other) : this() {
      bodyShape_ = other.bodyShape_;
      skinColor_ = other.skinColor_;
      hairColor_ = other.hairColor_;
      eyeColor_ = other.eyeColor_;
      wearables_ = other.wearables_.Clone();
      snapshots_ = other.snapshots_ != null ? other.snapshots_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvatarForUserData Clone() {
      return new AvatarForUserData(this);
    }

    /// <summary>Field number for the "body_shape" field.</summary>
    public const int BodyShapeFieldNumber = 1;
    private string bodyShape_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BodyShape {
      get { return bodyShape_; }
      set {
        bodyShape_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "skin_color" field.</summary>
    public const int SkinColorFieldNumber = 2;
    private string skinColor_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SkinColor {
      get { return skinColor_; }
      set {
        skinColor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "hair_color" field.</summary>
    public const int HairColorFieldNumber = 3;
    private string hairColor_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string HairColor {
      get { return hairColor_; }
      set {
        hairColor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "eye_color" field.</summary>
    public const int EyeColorFieldNumber = 4;
    private string eyeColor_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EyeColor {
      get { return eyeColor_; }
      set {
        eyeColor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "wearables" field.</summary>
    public const int WearablesFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_wearables_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> wearables_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Wearables {
      get { return wearables_; }
    }

    /// <summary>Field number for the "snapshots" field.</summary>
    public const int SnapshotsFieldNumber = 6;
    private global::Decentraland.Common.Sdk.Snapshots snapshots_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Decentraland.Common.Sdk.Snapshots Snapshots {
      get { return snapshots_; }
      set {
        snapshots_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AvatarForUserData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AvatarForUserData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BodyShape != other.BodyShape) return false;
      if (SkinColor != other.SkinColor) return false;
      if (HairColor != other.HairColor) return false;
      if (EyeColor != other.EyeColor) return false;
      if(!wearables_.Equals(other.wearables_)) return false;
      if (!object.Equals(Snapshots, other.Snapshots)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BodyShape.Length != 0) hash ^= BodyShape.GetHashCode();
      if (SkinColor.Length != 0) hash ^= SkinColor.GetHashCode();
      if (HairColor.Length != 0) hash ^= HairColor.GetHashCode();
      if (EyeColor.Length != 0) hash ^= EyeColor.GetHashCode();
      hash ^= wearables_.GetHashCode();
      if (snapshots_ != null) hash ^= Snapshots.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BodyShape.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(BodyShape);
      }
      if (SkinColor.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SkinColor);
      }
      if (HairColor.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(HairColor);
      }
      if (EyeColor.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(EyeColor);
      }
      wearables_.WriteTo(output, _repeated_wearables_codec);
      if (snapshots_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Snapshots);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BodyShape.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(BodyShape);
      }
      if (SkinColor.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SkinColor);
      }
      if (HairColor.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(HairColor);
      }
      if (EyeColor.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(EyeColor);
      }
      wearables_.WriteTo(ref output, _repeated_wearables_codec);
      if (snapshots_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Snapshots);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BodyShape.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BodyShape);
      }
      if (SkinColor.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SkinColor);
      }
      if (HairColor.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HairColor);
      }
      if (EyeColor.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EyeColor);
      }
      size += wearables_.CalculateSize(_repeated_wearables_codec);
      if (snapshots_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Snapshots);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AvatarForUserData other) {
      if (other == null) {
        return;
      }
      if (other.BodyShape.Length != 0) {
        BodyShape = other.BodyShape;
      }
      if (other.SkinColor.Length != 0) {
        SkinColor = other.SkinColor;
      }
      if (other.HairColor.Length != 0) {
        HairColor = other.HairColor;
      }
      if (other.EyeColor.Length != 0) {
        EyeColor = other.EyeColor;
      }
      wearables_.Add(other.wearables_);
      if (other.snapshots_ != null) {
        if (snapshots_ == null) {
          Snapshots = new global::Decentraland.Common.Sdk.Snapshots();
        }
        Snapshots.MergeFrom(other.Snapshots);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            BodyShape = input.ReadString();
            break;
          }
          case 18: {
            SkinColor = input.ReadString();
            break;
          }
          case 26: {
            HairColor = input.ReadString();
            break;
          }
          case 34: {
            EyeColor = input.ReadString();
            break;
          }
          case 42: {
            wearables_.AddEntriesFrom(input, _repeated_wearables_codec);
            break;
          }
          case 50: {
            if (snapshots_ == null) {
              Snapshots = new global::Decentraland.Common.Sdk.Snapshots();
            }
            input.ReadMessage(Snapshots);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            BodyShape = input.ReadString();
            break;
          }
          case 18: {
            SkinColor = input.ReadString();
            break;
          }
          case 26: {
            HairColor = input.ReadString();
            break;
          }
          case 34: {
            EyeColor = input.ReadString();
            break;
          }
          case 42: {
            wearables_.AddEntriesFrom(ref input, _repeated_wearables_codec);
            break;
          }
          case 50: {
            if (snapshots_ == null) {
              Snapshots = new global::Decentraland.Common.Sdk.Snapshots();
            }
            input.ReadMessage(Snapshots);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class UserData : pb::IMessage<UserData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UserData> _parser = new pb::MessageParser<UserData>(() => new UserData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UserData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Decentraland.Common.Sdk.UserDataReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserData(UserData other) : this() {
      displayName_ = other.displayName_;
      publicKey_ = other.publicKey_;
      hasConnectedWeb3_ = other.hasConnectedWeb3_;
      userId_ = other.userId_;
      version_ = other.version_;
      avatar_ = other.avatar_ != null ? other.avatar_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserData Clone() {
      return new UserData(this);
    }

    /// <summary>Field number for the "display_name" field.</summary>
    public const int DisplayNameFieldNumber = 1;
    private string displayName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DisplayName {
      get { return displayName_; }
      set {
        displayName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "public_key" field.</summary>
    public const int PublicKeyFieldNumber = 2;
    private string publicKey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PublicKey {
      get { return publicKey_ ?? ""; }
      set {
        publicKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "public_key" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPublicKey {
      get { return publicKey_ != null; }
    }
    /// <summary>Clears the value of the "public_key" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPublicKey() {
      publicKey_ = null;
    }

    /// <summary>Field number for the "has_connected_web3" field.</summary>
    public const int HasConnectedWeb3FieldNumber = 3;
    private bool hasConnectedWeb3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasConnectedWeb3 {
      get { return hasConnectedWeb3_; }
      set {
        hasConnectedWeb3_ = value;
      }
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 4;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 5;
    private int version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    /// <summary>Field number for the "avatar" field.</summary>
    public const int AvatarFieldNumber = 6;
    private global::Decentraland.Common.Sdk.AvatarForUserData avatar_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Decentraland.Common.Sdk.AvatarForUserData Avatar {
      get { return avatar_; }
      set {
        avatar_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UserData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UserData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DisplayName != other.DisplayName) return false;
      if (PublicKey != other.PublicKey) return false;
      if (HasConnectedWeb3 != other.HasConnectedWeb3) return false;
      if (UserId != other.UserId) return false;
      if (Version != other.Version) return false;
      if (!object.Equals(Avatar, other.Avatar)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DisplayName.Length != 0) hash ^= DisplayName.GetHashCode();
      if (HasPublicKey) hash ^= PublicKey.GetHashCode();
      if (HasConnectedWeb3 != false) hash ^= HasConnectedWeb3.GetHashCode();
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (Version != 0) hash ^= Version.GetHashCode();
      if (avatar_ != null) hash ^= Avatar.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DisplayName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DisplayName);
      }
      if (HasPublicKey) {
        output.WriteRawTag(18);
        output.WriteString(PublicKey);
      }
      if (HasConnectedWeb3 != false) {
        output.WriteRawTag(24);
        output.WriteBool(HasConnectedWeb3);
      }
      if (UserId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(UserId);
      }
      if (Version != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Version);
      }
      if (avatar_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Avatar);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DisplayName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DisplayName);
      }
      if (HasPublicKey) {
        output.WriteRawTag(18);
        output.WriteString(PublicKey);
      }
      if (HasConnectedWeb3 != false) {
        output.WriteRawTag(24);
        output.WriteBool(HasConnectedWeb3);
      }
      if (UserId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(UserId);
      }
      if (Version != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Version);
      }
      if (avatar_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Avatar);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DisplayName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DisplayName);
      }
      if (HasPublicKey) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PublicKey);
      }
      if (HasConnectedWeb3 != false) {
        size += 1 + 1;
      }
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (Version != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Version);
      }
      if (avatar_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Avatar);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UserData other) {
      if (other == null) {
        return;
      }
      if (other.DisplayName.Length != 0) {
        DisplayName = other.DisplayName;
      }
      if (other.HasPublicKey) {
        PublicKey = other.PublicKey;
      }
      if (other.HasConnectedWeb3 != false) {
        HasConnectedWeb3 = other.HasConnectedWeb3;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      if (other.Version != 0) {
        Version = other.Version;
      }
      if (other.avatar_ != null) {
        if (avatar_ == null) {
          Avatar = new global::Decentraland.Common.Sdk.AvatarForUserData();
        }
        Avatar.MergeFrom(other.Avatar);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DisplayName = input.ReadString();
            break;
          }
          case 18: {
            PublicKey = input.ReadString();
            break;
          }
          case 24: {
            HasConnectedWeb3 = input.ReadBool();
            break;
          }
          case 34: {
            UserId = input.ReadString();
            break;
          }
          case 40: {
            Version = input.ReadInt32();
            break;
          }
          case 50: {
            if (avatar_ == null) {
              Avatar = new global::Decentraland.Common.Sdk.AvatarForUserData();
            }
            input.ReadMessage(Avatar);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            DisplayName = input.ReadString();
            break;
          }
          case 18: {
            PublicKey = input.ReadString();
            break;
          }
          case 24: {
            HasConnectedWeb3 = input.ReadBool();
            break;
          }
          case 34: {
            UserId = input.ReadString();
            break;
          }
          case 40: {
            Version = input.ReadInt32();
            break;
          }
          case 50: {
            if (avatar_ == null) {
              Avatar = new global::Decentraland.Common.Sdk.AvatarForUserData();
            }
            input.ReadMessage(Avatar);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
