// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: decentraland/sdk/components/video_event.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DCL.ECSComponents {

  /// <summary>Holder for reflection information generated from decentraland/sdk/components/video_event.proto</summary>
  public static partial class VideoEventReflection {

    #region Descriptor
    /// <summary>File descriptor for decentraland/sdk/components/video_event.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VideoEventReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1kZWNlbnRyYWxhbmQvc2RrL2NvbXBvbmVudHMvdmlkZW9fZXZlbnQucHJv",
            "dG8SG2RlY2VudHJhbGFuZC5zZGsuY29tcG9uZW50cyJ0CgxQQlZpZGVvRXZl",
            "bnQSFgoOY3VycmVudF9vZmZzZXQYASABKAISFAoMdmlkZW9fbGVuZ3RoGAIg",
            "ASgCEjYKBXN0YXRlGAMgASgOMicuZGVjZW50cmFsYW5kLnNkay5jb21wb25l",
            "bnRzLlZpZGVvU3RhdGUqZwoKVmlkZW9TdGF0ZRILCgdWU19OT05FEAASDAoI",
            "VlNfRVJST1IQARIOCgpWU19MT0FESU5HEAISDAoIVlNfUkVBRFkQAxIOCgpW",
            "U19QTEFZSU5HEAQSEAoMVlNfQlVGRkVSSU5HEAVCFKoCEURDTC5FQ1NDb21w",
            "b25lbnRzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DCL.ECSComponents.VideoState), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DCL.ECSComponents.PBVideoEvent), global::DCL.ECSComponents.PBVideoEvent.Parser, new[]{ "CurrentOffset", "VideoLength", "State" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum VideoState {
    [pbr::OriginalName("VS_NONE")] VsNone = 0,
    [pbr::OriginalName("VS_ERROR")] VsError = 1,
    [pbr::OriginalName("VS_LOADING")] VsLoading = 2,
    [pbr::OriginalName("VS_READY")] VsReady = 3,
    [pbr::OriginalName("VS_PLAYING")] VsPlaying = 4,
    [pbr::OriginalName("VS_BUFFERING")] VsBuffering = 5,
  }

  #endregion

  #region Messages
  public sealed partial class PBVideoEvent : pb::IMessage<PBVideoEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PBVideoEvent> _parser = new pb::MessageParser<PBVideoEvent>(() => new PBVideoEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PBVideoEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DCL.ECSComponents.VideoEventReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBVideoEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBVideoEvent(PBVideoEvent other) : this() {
      currentOffset_ = other.currentOffset_;
      videoLength_ = other.videoLength_;
      state_ = other.state_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBVideoEvent Clone() {
      return new PBVideoEvent(this);
    }

    /// <summary>Field number for the "current_offset" field.</summary>
    public const int CurrentOffsetFieldNumber = 1;
    private float currentOffset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float CurrentOffset {
      get { return currentOffset_; }
      set {
        currentOffset_ = value;
      }
    }

    /// <summary>Field number for the "video_length" field.</summary>
    public const int VideoLengthFieldNumber = 2;
    private float videoLength_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float VideoLength {
      get { return videoLength_; }
      set {
        videoLength_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 3;
    private global::DCL.ECSComponents.VideoState state_ = global::DCL.ECSComponents.VideoState.VsNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DCL.ECSComponents.VideoState State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PBVideoEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PBVideoEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(CurrentOffset, other.CurrentOffset)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VideoLength, other.VideoLength)) return false;
      if (State != other.State) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CurrentOffset != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(CurrentOffset);
      if (VideoLength != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VideoLength);
      if (State != global::DCL.ECSComponents.VideoState.VsNone) hash ^= State.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CurrentOffset != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(CurrentOffset);
      }
      if (VideoLength != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(VideoLength);
      }
      if (State != global::DCL.ECSComponents.VideoState.VsNone) {
        output.WriteRawTag(24);
        output.WriteEnum((int) State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CurrentOffset != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(CurrentOffset);
      }
      if (VideoLength != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(VideoLength);
      }
      if (State != global::DCL.ECSComponents.VideoState.VsNone) {
        output.WriteRawTag(24);
        output.WriteEnum((int) State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CurrentOffset != 0F) {
        size += 1 + 4;
      }
      if (VideoLength != 0F) {
        size += 1 + 4;
      }
      if (State != global::DCL.ECSComponents.VideoState.VsNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PBVideoEvent other) {
      if (other == null) {
        return;
      }
      if (other.CurrentOffset != 0F) {
        CurrentOffset = other.CurrentOffset;
      }
      if (other.VideoLength != 0F) {
        VideoLength = other.VideoLength;
      }
      if (other.State != global::DCL.ECSComponents.VideoState.VsNone) {
        State = other.State;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            CurrentOffset = input.ReadFloat();
            break;
          }
          case 21: {
            VideoLength = input.ReadFloat();
            break;
          }
          case 24: {
            State = (global::DCL.ECSComponents.VideoState) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            CurrentOffset = input.ReadFloat();
            break;
          }
          case 21: {
            VideoLength = input.ReadFloat();
            break;
          }
          case 24: {
            State = (global::DCL.ECSComponents.VideoState) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
