// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: decentraland/sdk/components/video_event.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DCL.ECSComponents {

  /// <summary>Holder for reflection information generated from decentraland/sdk/components/video_event.proto</summary>
  public static partial class VideoEventReflection {

    #region Descriptor
    /// <summary>File descriptor for decentraland/sdk/components/video_event.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VideoEventReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1kZWNlbnRyYWxhbmQvc2RrL2NvbXBvbmVudHMvdmlkZW9fZXZlbnQucHJv",
            "dG8SG2RlY2VudHJhbGFuZC5zZGsuY29tcG9uZW50cyKcAQoMUEJWaWRlb0V2",
            "ZW50EhEKCXRpbWVzdGFtcBgBIAEoDRITCgt0aWNrX251bWJlchgCIAEoDRIW",
            "Cg5jdXJyZW50X29mZnNldBgDIAEoAhIUCgx2aWRlb19sZW5ndGgYBCABKAIS",
            "NgoFc3RhdGUYBSABKA4yJy5kZWNlbnRyYWxhbmQuc2RrLmNvbXBvbmVudHMu",
            "VmlkZW9TdGF0ZSqGAQoKVmlkZW9TdGF0ZRILCgdWU19OT05FEAASDAoIVlNf",
            "RVJST1IQARIOCgpWU19MT0FESU5HEAISDAoIVlNfUkVBRFkQAxIOCgpWU19Q",
            "TEFZSU5HEAQSEAoMVlNfQlVGRkVSSU5HEAUSDgoKVlNfU0VFS0lORxAGEg0K",
            "CVZTX1BBVVNFRBAHQhSqAhFEQ0wuRUNTQ29tcG9uZW50c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DCL.ECSComponents.VideoState), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DCL.ECSComponents.PBVideoEvent), global::DCL.ECSComponents.PBVideoEvent.Parser, new[]{ "Timestamp", "TickNumber", "CurrentOffset", "VideoLength", "State" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum VideoState {
    [pbr::OriginalName("VS_NONE")] VsNone = 0,
    [pbr::OriginalName("VS_ERROR")] VsError = 1,
    [pbr::OriginalName("VS_LOADING")] VsLoading = 2,
    [pbr::OriginalName("VS_READY")] VsReady = 3,
    [pbr::OriginalName("VS_PLAYING")] VsPlaying = 4,
    [pbr::OriginalName("VS_BUFFERING")] VsBuffering = 5,
    [pbr::OriginalName("VS_SEEKING")] VsSeeking = 6,
    [pbr::OriginalName("VS_PAUSED")] VsPaused = 7,
  }

  #endregion

  #region Messages
  public sealed partial class PBVideoEvent : pb::IMessage<PBVideoEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PBVideoEvent> _parser = new pb::MessageParser<PBVideoEvent>(() => new PBVideoEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PBVideoEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DCL.ECSComponents.VideoEventReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBVideoEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBVideoEvent(PBVideoEvent other) : this() {
      timestamp_ = other.timestamp_;
      tickNumber_ = other.tickNumber_;
      currentOffset_ = other.currentOffset_;
      videoLength_ = other.videoLength_;
      state_ = other.state_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBVideoEvent Clone() {
      return new PBVideoEvent(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private uint timestamp_;
    /// <summary>
    /// monotonic counter
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "tick_number" field.</summary>
    public const int TickNumberFieldNumber = 2;
    private uint tickNumber_;
    /// <summary>
    /// number of tick in which the event was produced, equals to EngineInfo.tick_number
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TickNumber {
      get { return tickNumber_; }
      set {
        tickNumber_ = value;
      }
    }

    /// <summary>Field number for the "current_offset" field.</summary>
    public const int CurrentOffsetFieldNumber = 3;
    private float currentOffset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float CurrentOffset {
      get { return currentOffset_; }
      set {
        currentOffset_ = value;
      }
    }

    /// <summary>Field number for the "video_length" field.</summary>
    public const int VideoLengthFieldNumber = 4;
    private float videoLength_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float VideoLength {
      get { return videoLength_; }
      set {
        videoLength_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 5;
    private global::DCL.ECSComponents.VideoState state_ = global::DCL.ECSComponents.VideoState.VsNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DCL.ECSComponents.VideoState State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PBVideoEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PBVideoEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      if (TickNumber != other.TickNumber) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(CurrentOffset, other.CurrentOffset)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VideoLength, other.VideoLength)) return false;
      if (State != other.State) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp != 0) hash ^= Timestamp.GetHashCode();
      if (TickNumber != 0) hash ^= TickNumber.GetHashCode();
      if (CurrentOffset != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(CurrentOffset);
      if (VideoLength != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VideoLength);
      if (State != global::DCL.ECSComponents.VideoState.VsNone) hash ^= State.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Timestamp != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Timestamp);
      }
      if (TickNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(TickNumber);
      }
      if (CurrentOffset != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(CurrentOffset);
      }
      if (VideoLength != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(VideoLength);
      }
      if (State != global::DCL.ECSComponents.VideoState.VsNone) {
        output.WriteRawTag(40);
        output.WriteEnum((int) State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Timestamp != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Timestamp);
      }
      if (TickNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(TickNumber);
      }
      if (CurrentOffset != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(CurrentOffset);
      }
      if (VideoLength != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(VideoLength);
      }
      if (State != global::DCL.ECSComponents.VideoState.VsNone) {
        output.WriteRawTag(40);
        output.WriteEnum((int) State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Timestamp);
      }
      if (TickNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TickNumber);
      }
      if (CurrentOffset != 0F) {
        size += 1 + 4;
      }
      if (VideoLength != 0F) {
        size += 1 + 4;
      }
      if (State != global::DCL.ECSComponents.VideoState.VsNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PBVideoEvent other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0) {
        Timestamp = other.Timestamp;
      }
      if (other.TickNumber != 0) {
        TickNumber = other.TickNumber;
      }
      if (other.CurrentOffset != 0F) {
        CurrentOffset = other.CurrentOffset;
      }
      if (other.VideoLength != 0F) {
        VideoLength = other.VideoLength;
      }
      if (other.State != global::DCL.ECSComponents.VideoState.VsNone) {
        State = other.State;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Timestamp = input.ReadUInt32();
            break;
          }
          case 16: {
            TickNumber = input.ReadUInt32();
            break;
          }
          case 29: {
            CurrentOffset = input.ReadFloat();
            break;
          }
          case 37: {
            VideoLength = input.ReadFloat();
            break;
          }
          case 40: {
            State = (global::DCL.ECSComponents.VideoState) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Timestamp = input.ReadUInt32();
            break;
          }
          case 16: {
            TickNumber = input.ReadUInt32();
            break;
          }
          case 29: {
            CurrentOffset = input.ReadFloat();
            break;
          }
          case 37: {
            VideoLength = input.ReadFloat();
            break;
          }
          case 40: {
            State = (global::DCL.ECSComponents.VideoState) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
