export const OPUS_BITS_PER_SECOND = 24000
export const OPUS_FRAME_SIZE_MS = 60

export const OPUS_SAMPLES_PER_FRAME = (OPUS_BITS_PER_SECOND * OPUS_FRAME_SIZE_MS) / 1000

export const VOICE_CHAT_SAMPLE_RATE = 24000

export const OUTPUT_NODE_BUFFER_SIZE = 4096
export const OUTPUT_NODE_BUFFER_DURATION = (OUTPUT_NODE_BUFFER_SIZE * 1000) / VOICE_CHAT_SAMPLE_RATE

export const INPUT_NODE_BUFFER_SIZE = 4096
