# This pipeline is triggered after the CDN has succeed uploading a built package

name: Set delivery rollout

on: [deployment_status]

jobs:
  set-rollouts-automatic:
    if: ${{ github.event.deployment.task == 'upload-to-cdn' && github.event.deployment_status.state == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: set-rollout-zone
        if: ${{ github.event.deployment.payload.packageTag == 'next' }}
        uses: decentraland/set-rollout-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Repo deployment info
          ref: ${{ github.event.deployment.ref }}
          sha: ${{ github.event.deployment.sha }}

          # CDN information
          packageName: ${{ github.event.deployment.payload.packageName }}
          packageVersion: ${{ github.event.deployment.payload.packageVersion }}

          # Rollout information
          deploymentDomain: "play.decentraland.zone"
          deploymentName: "@dcl/explorer"
          percentage: 100

      - name: set-rollout-today
        if: ${{ github.event.deployment.payload.packageTag == 'next' }}
        uses: decentraland/set-rollout-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Repo deployment info
          ref: ${{ github.event.deployment.ref }}
          sha: ${{ github.event.deployment.sha }}

          # CDN information
          packageName: ${{ github.event.deployment.payload.packageName }}
          packageVersion: ${{ github.event.deployment.payload.packageVersion }}

          # Rollout information
          deploymentDomain: "play.decentraland.today"
          deploymentName: "@dcl/explorer"
          percentage: 100

      - name: set-rollout-org
        if: ${{ github.event.deployment.payload.packageTag == 'latest' }}
        uses: decentraland/set-rollout-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Repo deployment info
          ref: ${{ github.event.deployment.ref }}
          sha: ${{ github.event.deployment.sha }}

          # CDN information
          packageName: ${{ github.event.deployment.payload.packageName }}
          packageVersion: ${{ github.event.deployment.payload.packageVersion }}

          # Rollout information
          deploymentDomain: "play.decentraland.org"
          deploymentName: "@dcl/explorer"
          percentage: 0
