name: Create PR for syncing main to dev

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create or update branch
        run: |
          git checkout -B chore/sync
          git push --force --set-upstream origin chore/sync
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "chore/sync"                          # If blank, default: triggered branch
          destination_branch: "dev"                            # If blank, default: master
          pr_title: "chore: sync main to dev" # Title of pull request
          pr_body: |                                           # Full markdown support, requires pr_title to be set
            :crown: *An automated PR*
          pr_label: "auto-pr"                                  # Comma-separated list (no spaces)
          pr_draft: false                                      # Creates pull request as draft
          pr_allow_empty: false                                # Creates pull request even if there are no changes
          github_token: ${{ github.token }}                    # If blank, default: secrets.GITHUB_TOKEN